# Generated by Django 4.2 on 2023-04-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Выберите ингредиент', max_length=200, verbose_name='Наименование ингредиента'),
        ),
    ]
