# Generated by Django 4.2 on 2023-04-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredientcount_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientcount',
            old_name='name',
            new_name='ingredient',
        ),
    ]
