# Generated by Django 4.2 on 2023-05-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredientcount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='%Y/%m/%d', verbose_name='Картинка'),
        ),
    ]
